#pragma once

#define MASK_AS_PF 1
#define NO_CD_FIX 1
#define NO_INTRO 1
#define LEVELS_AUTODOWNLOADER 1
#define CAMERA_1_3_COMMANDS 0
#define SPECTATE_MODE_ENABLE 1
#define SPECTATE_MODE_SHOW_WEAPON 1
#define SPLITSCREEN_ENABLE 0
#define WINDOWED_MODE_SUPPORT 1
#define MULTISAMPLING_SUPPORT 1
#define ANISOTROPIC_FILTERING 1
#define DIRECTINPUT_SUPPORT 1
#define DIRECTINPUT_ENABLED 0
#define WIDESCREEN_FIX 1

#define CONSOLE_BG_R 0x00
#define CONSOLE_BG_G 0x00
#define CONSOLE_BG_B 0x40
#define CONSOLE_BG_A 0xC0
