#pragma once

#define IDD_MAIN_FRAME_TOP_BAR 136
#define IDD_TRIGGER_PROPERTIES 148

#define IDC_TRIGGER_SCRIPT_NAME 1042
#define IDC_TRIGGER_SOLO 2000
#define IDC_TRIGGER_CLIENTSIDE 2001
#define IDC_TRIGGER_TELEPORT 2002
